/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cocos2dx_cpp_SDKPlugin */

#ifndef _Included_org_cocos2dx_cpp_SDKPlugin
#define _Included_org_cocos2dx_cpp_SDKPlugin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cocos2dx_cpp_SDKPlugin
 * Method:    LoginCallback
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cocos2dx_cpp_SDKPlugin_LoginCallback
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     org_cocos2dx_cpp_SDKPlugin
 * Method:    paySecessCallback
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_cocos2dx_cpp_SDKPlugin_paySecessCallback
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
